[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bike-gru-experiments"
version = "0.1.0"
dependencies = [
    "torch",
    "numpy",
    "pandas",
    "matplotlib",
    "pyyaml",
]